### PR TITLE
[LC-44] add websocket route for node dispatcher

### PR DESCRIPTION
**Pull request by laurenceyoon**
## Add websocket connection between citizen node and mother peer

* How it works
  * The websocket connection replaces the existing `node_Subscribe` and `node_AnnounceConfirmedBlock`.
  * After the block height sync of the Citizen node is over, Citizen sends a subscribe request to the websocket, bypassing its current block height. (loopchain side)
  * **This request is received from the icon-rpc-server dispatcher of the mother peer, and it passes the block data whenever a new block is generated.** (update from this branch)

* For compatibility, the existing jsonrpc functions remain for some time.

### CODE REVIEW

**Review by inwonkim — APPROVED** [review]

**Comment by yakkle** [comment]
@laurenceyoon 
please update title start with jira issue number.

**Review by cow-hs — APPROVED** [review]
I understand, Good!

**Review by inwonkim — CHANGES_REQUESTED** [review]
should add route `(NodeDispatcher.websocket_dispatch, 'api/node/')`

**Comment by laurenceyoon** [comment]
@inwonkim deleted all `strict_slashes` usages as it's default option

**Review by inwonkim — APPROVED** [review]

**Review by yakkle — APPROVED** [review]

**Pull request merged**
